### ISSUE TITLE
TypeError when FieldtypeOptionsColor set to required

### ISSUE THREAD

**Issue by tobisalad** [kixe/FieldtypeColor#8]
When I create a FieldtypeOptionsColor-field and set it to required I get the following error:
```
Fatal Error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, int given in /site/modules/FieldtypeColor/FieldtypeOptionsColor.module:120 
Stack trace: 
#0 [...]/site/modules/FieldtypeColor/FieldtypeOptionsColor.module(120): count() 
#1 [...]/wire/core/Field.php(975): ProcessWire\FieldtypeOptionsColor->getInputfield() 
#2 [...]/wire/core/Wire.php(417): ProcessWire\Field->___getInputfield() 
#3 [...]/wire/core/WireHooks.php(951): ProcessWire\Wire->_callMethod() 
#4 [...]/wire/core/Wire.php(485): ProcessWire\WireHooks->runHooks() 
#5 [...]/wire/modules/Process/ProcessField/ProcessField.module(1385): ProcessWire\Wire->__call() 
#6 [...]/wire/modules/Process/ProcessField/ProcessField.module(1257): ProcessWire\ProcessField->buildEditFormAllowedContexts() 
#7 [...]/wire/core/Wire.php(417): ProcessWire\ProcessField->___buildEditFormContext() 
#8 [...]/wire/core/WireHooks.php(951): ProcessWire\Wire->_callMethod() 
#9 [...]/wire/core/Wire.php(485): ProcessWire\WireHooks->runHooks() 
#10 [...]/wire/modules/Process/ProcessField/ProcessField.module(1115): ProcessWire\Wire->__call() 
#11 [...]/wire/core/Wire.php(414): ProcessWire\ProcessField->___buildEditForm() 
#12 [...]/wire/core/WireHooks.php(951): ProcessWire\Wire->_callMethod() 
#13 [...]/wire/core/Wire.php(485): ProcessWire\WireHooks->runHooks() 
#14 [...]/wire/modules/Process/ProcessField/ProcessField.module(796): ProcessWire\Wire->__call() 
#15 [...]/wire/core/Wire.php(414): ProcessWire\ProcessField->___executeEdit() 
#16 [...]/wire/core/WireHooks.php(951): ProcessWire\Wire->_callMethod() 
#17 [...]/wire/core/Wire.php(485): ProcessWire\WireHooks->runHooks() 
#18 [...]/wire/core/ProcessController.php(337): ProcessWire\Wire->__call() 
#19 [...]/wire/core/Wire.php(414): ProcessWire\ProcessController->___execute() 
#20 [...]/wire/core/WireHooks.php(951): ProcessWire\Wire->_callMethod() 
#21 [...]/wire/core/Wire.php(485): ProcessWire\WireHooks->runHooks() 
#22 [...]/wire/core/admin.php(160): ProcessWire\Wire->__call() 
#23 [...]/site/templates/admin.php(18): require('...') 
#24 [...]/wire/core/TemplateFile.php(327): require('...') 
#25 [...]/wire/core/Wire.php(414): ProcessWire\TemplateFile->___render() 
#26 [...]/wire/core/WireHooks.php(951): ProcessWire\Wire->_callMethod() 
#27 [...]/wire/core/Wire.php(485): ProcessWire\WireHooks->runHooks() 
#28 [...]/wire/modules/PageRender.module(575): ProcessWire\Wire->__call() 
#29 [...]/wire/core/Wire.php(417): ProcessWire\PageRender->___renderPage() 
#30 [...]/wire/core/WireHooks.php(951): ProcessWire\Wire->_callMethod() 
#31 [...]/wire/core/Wire.php(485): ProcessWire\WireHooks->runHooks() 
#32 [...]/wire/core/WireHooks.php(1059): ProcessWire\Wire->__call() 
#33 [...]/wire/core/Wire.php(485): ProcessWire\WireHooks->runHooks() 
#34 [...]/wire/modules/Process/ProcessPageView.module(184): ProcessWire\Wire->__call() 
#35 [...]/wire/modules/Process/ProcessPageView.module(114): ProcessWire\ProcessPageView->renderPage() 
#36 [...]/wire/core/Wire.php(417): ProcessWire\ProcessPageView->___execute() 
#37 [...]/wire/core/WireHooks.php(951): ProcessWire\Wire->_callMethod() 
#38 [...]/wire/core/Wire.php(485): ProcessWire\WireHooks->runHooks() 
#39 [...]/index.php(55): ProcessWire\Wire->__call() 
#40 {main}   thrown (line 120 of /site/modules/FieldtypeColor/FieldtypeOptionsColor.module)

```
Processwire-version: 3.0.200
PHP-version: 8.0

**Comment by kixe** [comment]
Fixed

**Comment by tobisalad** [comment]
Thanks!
